version: '3.8'

volumes:
    pg-data: { }

services:
    web:
        container_name: real_estate_agency_nginx
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - "8182:80"
        restart: always
        depends_on:
            - php-fpm
            - postgres

    php-fpm:
        container_name: real_estate_agency_php-fpm
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - .:/var/www/html
        environment:
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_HOST: ${DB_HOST}
            DB_PASSWORD: ${DB_PASSWORD}
        extra_hosts:
            - host.docker.internal:host-gateway

    postgres:
        container_name: real_estate_agency_postgres
        image: public.ecr.aws/docker/library/postgres:15-alpine
        hostname: database
        restart: always
        volumes:
            - ./.docker/postgres:/docker-entrypoint-initdb.d
            - pg-data:/var/lib/postgresql/data:rw
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5431:5432"

    pgadmin:
        container_name: real_estate_agency_pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_LISTEN_ADDRESS=${PGADMIN_LISTEN_ADDRESS}
        ports:
            - "8282:80"
        depends_on:
            - postgres
